# SurvivalTrader config.yml
# Ванильный магазин и аукцион на предметах для Paper 1.21

gui:
  shop-title: "Survival Shop"
  auction-title: "Auction"
  auction-preview-title: "Auction Preview"

shop:
  # Таймер обновления ассортимента (секунды)
  update-interval: 60   # продакшн: 3600

  # Сколько товаров показывать при каждом обновлении
  items-per-update: 12

  # Список возможных товаров магазина (рандомно выбираются items-per-update штук)
  possible-items:
    - item: BREAD
      amount: 16
      price: 10
    - item: COOKED_BEEF
      amount: 8
      price: 20
    - item: IRON_PICKAXE
      amount: 1
      price: 50
    - item: OAK_LOG
      amount: 32
      price: 15
    - item: IRON_INGOT
      amount: 10
      price: 30
    - item: SHIELD
      amount: 1
      price: 25
    - item: TORCH
      amount: 64
      price: 5
    - item: ARROW
      amount: 32
      price: 10
    - item: COOKED_PORKCHOP
      amount: 8
      price: 20
    - item: BOW
      amount: 1
      price: 35
    - item: FISHING_ROD
      amount: 1
      price: 25
    - item: BUNDLE
      amount: 1
      price: 40

  # Белый список валют магазина (только простые и дешёвые ресурсы)
  allowed-bid-items:
    - DIRT
    - COBBLESTONE
    - STONE
    - SAND
    - OAK_LOG

  # Лимиты и анти-спам
  max-purchases-per-item: 10           # на игрока за обновление ассортимента
  global-max-purchases-per-item: 20    # общий лимит на товар
  anti-spam-cooldown: 10               # сек

auction:
  # Длительность аукциона (секунды)
  duration: 300        # продакшн: 18000 (5 часов)

  anti-spam-cooldown: 10
  troll-chance: 30
  fake-bid-item: DIRT
  min-bid-base: 1

  # Лоты всегда дорогие: из списка op-lots или сгенерированный алмазный шмот с чарами
  op-lots:
    - TOTEM_OF_UNDYING
    - ELYTRA
    - NETHERITE_SWORD
    - BEACON
    - ENCHANTED_GOLDEN_APPLE
    - NETHERITE_PICKAXE
    - NETHERITE_CHESTPLATE
    - ENCHANTED_BOOK

  # Генерировать ли случайный алмазный предмет с чарами как один из вариантов лота
  generate-diamond-gear: true

  # Ротация валют (off | daily | hourly)
  bid-rotation: daily

  # Пул редких/дорогих валют для аукциона (используется при rotation/рандоме)
  bid-items:
    - DIAMOND
    - EMERALD
    - NETHERITE_INGOT
    - NETHERITE_SCRAP
    - ANCIENT_DEBRIS
    - ENCHANTED_GOLDEN_APPLE

  # Режим выбора валюты, если bid-rotation: off (random | fixed)
  bid-item-mode: random
  fixed-bid-item: DIAMOND

  # BossBar таймер аукциона
  bossbar:
    enabled: true
    title: "Аукцион: %lot% | %biditem% | макс %max% | %left%"
    color: GREEN           # базовый цвет; при убывании времени меняется на YELLOW/RED
    style: SEGMENTED_10

  # Возвраты депозитов проигравшим сохранять для оффлайна
  persist-returns-for-offline-losers: true

messages:
  # Магазин
  shop-update: "§aМагазин обновлён! Новые товары в /shop."
  success-buy: "§aОбмен успешен! Отдали %price% %biditem% за %amount% %item%."
  no-items: "§cНедостаточно %biditem% (нужно %price%)!"
  anti-spam: "§cПодожди %time% сек."
  limit-reached: "§cЛимит достигнут!"
  inventory-full: "§cНедостаточно места в инвентаре!"
  shop-timeleft: "§7Обновление магазина через %time%."

  # Аукцион
  new-auction: "§aНовый аукцион! Лот: %lot%. Ставки в %biditem% (мин. %minbid%)."
  new-auction-troll: "§aНовый аукцион! Лот: Эпический Шалкер с сетом бога! Ставки в %fakebiditem% (мин. %minbid%)."
  bid-success: "§aСтавка принята! (Эффективно: %effective%)."
  bid-too-low: "§cСтавка мала! Минимум: %min%."
  auction-end: "§aАукцион завершён! Победитель: %winner% с %amount% %biditem%. Лот: %lot%."
  auction-end-troll: "§aТролль! Ставки возвращены."
  no-bids: "§aАукцион завершён без ставок."
  returned: "§aВозвращено: %amount% %biditem%."
  reward-saved: "§aВаш приз сохранён и будет выдан при входе."
  reward-claimed: "§aВы получили сохранённый приз с аукциона!"
  auction-timeleft: "§7До конца аукциона: %time%."
  cannot-decrease-bid: "§cНельзя уменьшать свою ставку."
